chore(deps): bump immutable from 5.0.3 to 5.1.1 (#6479)
Bumps [immutable](https://github.com/immutable-js/immutable-js) from 5.0.3 to 5.1.1.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/immutable-js/immutable-js/releases">immutable's releases</a>.</em></p>
<blockquote>
<h2>v5.1.1</h2>
<h2>What's Changed</h2>
<p>Fix issue in builded types files in 5.1.0 due to cpy-cli upgrade</p>
<p><strong>Full Changelog</strong>: <a href="https://github.com/immutable-js/immutable-js/compare/v5.1.0...v5.1.1">https://github.com/immutable-js/immutable-js/compare/v5.1.0...v5.1.1</a></p>
<h2>v5.1.0</h2>
<h2>What's Changed</h2>
<ul>
<li>Add shuffle to list <a href="https://redirect.github.com/immutable-js/immutable-js/pull/2066">#2066</a> by <a href="https://github.com/mazerty"><code>@​mazerty</code></a></li>
<li>TypeScript: Better getIn <code>RetrievePath</code> <a href="https://redirect.github.com/immutable-js/immutable-js/pull/2070">#2070</a> by <a href="https://github.com/jdeniau"><code>@​jdeniau</code></a></li>
<li>Fix <a href="https://redirect.github.com/immutable-js/immutable-js/issues/1915">#1915</a> &quot;Converting a Seq to a list causes RangeError (max call size exceeded)&quot; by <a href="https://github.com/alexvictoor"><code>@​alexvictoor</code></a> in <a href="https://redirect.github.com/immutable-js/immutable-js/pull/2038">#2038</a></li>
<li>TypeScript: Fix proper typings for Seq.concat() <a href="https://redirect.github.com/immutable-js/immutable-js/pull/2040">#2040</a> by <a href="https://github.com/alexvictoor"><code>@​alexvictoor</code></a></li>
<li>Fix Uncaught &quot;TypeError: keyPath.slice is not a function&quot; for ArrayLike method <a href="https://redirect.github.com/immutable-js/immutable-js/pull/2065">#2065</a> by <a href="https://github.com/jdeniau"><code>@​jdeniau</code></a></li>
</ul>
<h3>Internal</h3>
<ul>
<li>Upgrade typescript and typescript-eslint <a href="https://redirect.github.com/immutable-js/immutable-js/pull/2046">#2046</a> by <a href="https://github.com/jdeniau"><code>@​jdeniau</code></a></li>
<li>Upgrade to rollup 4 <a href="https://redirect.github.com/immutable-js/immutable-js/pull/2049">#2049</a> by <a href="https://github.com/jdeniau"><code>@​jdeniau</code></a></li>
<li>Start migrating codebase to TypeScript without any runtime change nor .d.ts change:
<ul>
<li>allow TS files to be compiled in src dir <a href="https://redirect.github.com/immutable-js/immutable-js/pull/2054">#2054</a> by <a href="https://github.com/jdeniau"><code>@​jdeniau</code></a></li>
</ul>
</li>
<li>add exception for code that should not happen in updateIn <a href="https://redirect.github.com/immutable-js/immutable-js/pull/2074">#2074</a> by <a href="https://github.com/jdeniau"><code>@​jdeniau</code></a></li>
<li>Reformat Range.toString for readability <a href="https://redirect.github.com/immutable-js/immutable-js/pull/2075">#2075</a> by <a href="https://github.com/ustinvaskin"><code>@​Ustin.Vaskin</code></a></li>
</ul>
<h2>New Contributors</h2>
<ul>
<li><a href="https://github.com/mazerty"><code>@​mazerty</code></a> made their first contribution in <a href="https://redirect.github.com/immutable-js/immutable-js/pull/2066">immutable-js/immutable-js#2066</a></li>
<li><a href="https://github.com/ustinvaskin"><code>@​ustinvaskin</code></a> made their first contribution in <a href="https://redirect.github.com/immutable-js/immutable-js/pull/2075">immutable-js/immutable-js#2075</a></li>
</ul>
<p><strong>Full Changelog</strong>: <a href="https://github.com/immutable-js/immutable-js/compare/v5.0.2...v5.1.0">https://github.com/immutable-js/immutable-js/compare/v5.0.2...v5.1.0</a></p>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a href="https://github.com/immutable-js/immutable-js/blob/main/CHANGELOG.md">immutable's changelog</a>.</em></p>
<blockquote>
<h2>5.1.1</h2>
<ul>
<li>Fix type copying</li>
</ul>
<h2>5.1.0</h2>
<ul>
<li>Add shuffle to list <a href="https://redirect.github.com/immutable-js/immutable-js/pull/2066">#2066</a> by <a href="https://github.com/mazerty"><code>@​mazerty</code></a></li>
<li>TypeScript: Better getIn <code>RetrievePath</code> <a href="https://redirect.github.com/immutable-js/immutable-js/pull/2070">#2070</a> by <a href="https://github.com/jdeniau"><code>@​jdeniau</code></a></li>
<li>Fix <a href="https://redirect.github.com/immutable-js/immutable-js/issues/1915">#1915</a> &quot;Converting a Seq to a list causes RangeError (max call size exceeded)&quot; by <a href="https://github.com/alexvictoor"><code>@​alexvictoor</code></a> in <a href="https://redirect.github.com/immutable-js/immutable-js/pull/2038">#2038</a></li>
<li>TypeScript: Fix proper typings for Seq.concat() <a href="https://redirect.github.com/immutable-js/immutable-js/pull/2040">#2040</a> by <a href="https://github.com/alexvictoor"><code>@​alexvictoor</code></a></li>
<li>Fix Uncaught &quot;TypeError: keyPath.slice is not a function&quot; for ArrayLike method <a href="https://redirect.github.com/immutable-js/immutable-js/pull/2065">#2065</a> by <a href="https://github.com/jdeniau"><code>@​jdeniau</code></a></li>
</ul>
<h3>Internal</h3>
<ul>
<li>Upgrade typescript and typescript-eslint <a href="https://redirect.github.com/immutable-js/immutable-js/pull/2046">#2046</a> by <a href="https://github.com/jdeniau"><code>@​jdeniau</code></a></li>
<li>Upgrade to rollup 4 <a href="https://redirect.github.com/immutable-js/immutable-js/pull/2049">#2049</a> by <a href="https://github.com/jdeniau"><code>@​jdeniau</code></a></li>
<li>Start migrating codebase to TypeScript without any runtime change nor .d.ts change:
<ul>
<li>allow TS files to be compiled in src dir <a href="https://redirect.github.com/immutable-js/immutable-js/pull/2054">#2054</a> by <a href="https://github.com/jdeniau"><code>@​jdeniau</code></a></li>
</ul>
</li>
<li>add exception for code that should not happen in updateIn <a href="https://redirect.github.com/immutable-js/immutable-js/pull/2074">#2074</a> by <a href="https://github.com/jdeniau"><code>@​jdeniau</code></a></li>
<li>Reformat Range.toString for readability <a href="https://redirect.github.com/immutable-js/immutable-js/pull/2075">#2075</a> by <a href="https://github.com/ustinvaskin"><code>@​Ustin.Vaskin</code></a></li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/immutable-js/immutable-js/commit/829b2ee566bb8fe5e487b1593e2011d8058cf9c1"><code>829b2ee</code></a> 5.1.1</li>
<li><a href="https://github.com/immutable-js/immutable-js/commit/9fa2f20766b34cead981b9ea21a79572faf58066"><code>9fa2f20</code></a> fix type copying</li>
<li><a href="https://github.com/immutable-js/immutable-js/commit/bed5ccd6676e84e43fc1055005ec4d6dc82e9106"><code>bed5ccd</code></a> changelog</li>
<li><a href="https://github.com/immutable-js/immutable-js/commit/850af73be0ea30e2c02e4fe82ef64c4f4beddf61"><code>850af73</code></a> 5.1.0</li>
<li><a href="https://github.com/immutable-js/immutable-js/commit/f0581b2555ec22d0a4e9a99aaf08bcb81f1a6d0c"><code>f0581b2</code></a> changelog</li>
<li><a href="https://github.com/immutable-js/immutable-js/commit/d4189ab12e44e44b5f9ec724b303df5115f44e07"><code>d4189ab</code></a> Merge branch 'ustinvaskin-upd-range-toString-ternary'</li>
<li><a href="https://github.com/immutable-js/immutable-js/commit/e2009174e43952c1761593b5cab7c5885608fa53"><code>e200917</code></a> add tests for Range.toString()</li>
<li><a href="https://github.com/immutable-js/immutable-js/commit/bc52ed97d60d16d717371832b814a72b397cc40c"><code>bc52ed9</code></a> Update Range.js</li>
<li><a href="https://github.com/immutable-js/immutable-js/commit/70826e6436a81d4a2344439af0fab57c3db50b50"><code>70826e6</code></a> Migrate functional files to TS (<a href="https://redirect.github.com/immutable-js/immutable-js/issues/2063">#2063</a>)</li>
<li><a href="https://github.com/immutable-js/immutable-js/commit/5b932ce37843503350784c0345673764900e2acc"><code>5b932ce</code></a> changelog</li>
<li>Additional commits viewable in <a href="https://github.com/immutable-js/immutable-js/compare/v5.0.3...v5.1.1">compare view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=immutable&package-manager=npm_and_yarn&previous-version=5.0.3&new-version=5.1.1)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't alter it yourself. You can also trigger a rebase manually by commenting `@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop Dependabot creating any more for this major version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop Dependabot creating any more for this minor version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop Dependabot creating any more for this dependency (unless you reopen the PR or upgrade to it yourself)


</details>